import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { FaUserCircle } from "react-icons/fa";

import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import SocialNav from "@/components/SocialNav";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-poppins',
});


export const metadata: Metadata = { 
  title: "Joshua Napinas - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <div className="p-4 bg-[#161616] box-border">
          <Header>
            <FaUserCircle className="w-8 h-8 text-gray-200 hover:text-white" />
            <Navbar />
            <SocialNav />
          </Header>
          {children}
        </div>
      </body>
    </html>
  );
}

